/*!
 *
 * Copyright (c) 2009-2013, Kirix Research, LLC.  All rights reserved.
 *
 * Project:  Application Client
 * Author:   Benjamin I. Williams
 * Created:  2009-08-29
 *
 */


// no header protector

#ifndef BEGIN_COMMANDS
#define BEGIN_COMMANDS(definefunc, startid) extern void definefunc(); enum { ID_DummyCommand_##definefunc = startid
#define END_COMMANDS() };
#define DEFINE_COMMAND(tag, id) ,id
#define DEFINE_COMMAND_HIDDEN(tag, id) ,id
#endif

BEGIN_COMMANDS(defineCommandsMain, 20000)

DEFINE_COMMAND("app.first",                    ID_App_First)
DEFINE_COMMAND("app.create_project",           ID_App_CreateProject)
DEFINE_COMMAND("app.open_project",             ID_App_OpenProject)
DEFINE_COMMAND("app.job_scheduler",            ID_App_JobScheduler)
DEFINE_COMMAND("app.job_manager",              ID_App_JobManager)
DEFINE_COMMAND("app.extension_manager",        ID_App_ExtensionManager)
DEFINE_COMMAND("app.license_manager",          ID_App_LicenseManager)
DEFINE_COMMAND("app.check_for_updates",        ID_App_CheckForUpdates)
DEFINE_COMMAND("app.options",                  ID_App_Options)
DEFINE_COMMAND("app.toggle_protect",           ID_App_ToggleProtect)
DEFINE_COMMAND("app.toggle_relationship_sync", ID_App_ToggleRelationshipSync)
DEFINE_COMMAND("app.relationship_sync_none",   ID_App_RelationshipSyncNone)
DEFINE_COMMAND("app.relationship_sync_filter", ID_App_RelationshipSyncFilter)
DEFINE_COMMAND("app.relationship_sync_seek",   ID_App_RelationshipSyncSeek)
DEFINE_COMMAND("app.exit",                     ID_App_Exit)
DEFINE_COMMAND("app.about",                    ID_App_About)
DEFINE_COMMAND("app.start_record",             ID_App_StartRecord)
DEFINE_COMMAND("app.stop_record",              ID_App_StopRecord)
DEFINE_COMMAND("app.sign_in",                  ID_App_SignIn)
DEFINE_COMMAND("app.last",                     ID_App_Last)


DEFINE_COMMAND("canvas.first",                 ID_Canvas_First)
DEFINE_COMMAND("canvas.object_align_left",     ID_Canvas_ObjectAlignLeft)
DEFINE_COMMAND("canvas.object_align_center",   ID_Canvas_ObjectAlignCenter)
DEFINE_COMMAND("canvas.object_align_right",    ID_Canvas_ObjectAlignRight)
DEFINE_COMMAND("canvas.object_align_top",      ID_Canvas_ObjectAlignTop)
DEFINE_COMMAND("canvas.object_align_middle",   ID_Canvas_ObjectAlignMiddle)
DEFINE_COMMAND("canvas.object_align_bottom",   ID_Canvas_ObjectAlignBottom)
DEFINE_COMMAND("canvas.object_send_to_back",   ID_Canvas_ObjectSendToBack)
DEFINE_COMMAND("canvas.object_send_backward",  ID_Canvas_ObjectSendBackward)
DEFINE_COMMAND("canvas.object_bring_to_front", ID_Canvas_ObjectBringToFront)
DEFINE_COMMAND("canvas.object_bring_forward",  ID_Canvas_ObjectBringForward)
DEFINE_COMMAND("canvas.last",                  ID_Canvas_Last)


DEFINE_COMMAND("data.first",                   ID_Data_First)
DEFINE_COMMAND("data.sort",                    ID_Data_Sort)
DEFINE_COMMAND("data.sort_ascending",          ID_Data_SortAscending)
DEFINE_COMMAND("data.sort_descending",         ID_Data_SortDescending)
DEFINE_COMMAND("data.remove_sort",             ID_Data_RemoveSort)
DEFINE_COMMAND("data.remove_sort_filter",      ID_Data_RemoveSortFilter)
DEFINE_COMMAND("data.filter",                  ID_Data_Filter)
DEFINE_COMMAND("data.quick_filter",            ID_Data_QuickFilter)
DEFINE_COMMAND("data.mark_records",            ID_Data_MarkRecords)
DEFINE_COMMAND("data.copy_records",            ID_Data_CopyRecords)
DEFINE_COMMAND("data.append_records",          ID_Data_AppendRecords)
DEFINE_COMMAND("data.update_records",          ID_Data_UpdateRecords)
DEFINE_COMMAND("data.delete_records",          ID_Data_DeleteRecords)
DEFINE_COMMAND("data.group_records",           ID_Data_GroupRecords)
DEFINE_COMMAND("data.create_dynamic_field",    ID_Data_CreateDynamicField)
DEFINE_COMMAND("data.modify_dynamic_field",    ID_Data_ModifyDynamicField)
DEFINE_COMMAND("data.make_dynamic_field_static", ID_Data_MakeDynamicFieldStatic)
DEFINE_COMMAND("data.delete_field",            ID_Data_DeleteField)
DEFINE_COMMAND("data.edit_indexes",            ID_Data_EditIndexes)
DEFINE_COMMAND("data.edit_structure",          ID_Data_EditStructure)
DEFINE_COMMAND("data.summary",                 ID_Data_Summary)
DEFINE_COMMAND("data.last",                    ID_Data_Last)



DEFINE_COMMAND("edit.first",           ID_Edit_First)
DEFINE_COMMAND("edit.undo",            ID_Edit_Undo)
DEFINE_COMMAND("edit.redo",            ID_Edit_Redo)
DEFINE_COMMAND("edit.cut",             ID_Edit_Cut)
DEFINE_COMMAND("edit.copy",            ID_Edit_Copy)
DEFINE_COMMAND("edit.copy_link",       ID_Edit_CopyLink)
DEFINE_COMMAND("edit.paste",           ID_Edit_Paste)
DEFINE_COMMAND("edit.find",            ID_Edit_Find)
DEFINE_COMMAND("edit.delete",          ID_Edit_Delete)
DEFINE_COMMAND("edit.select_all",      ID_Edit_SelectAll)
DEFINE_COMMAND("edit.select_none",     ID_Edit_SelectNone)
DEFINE_COMMAND("edit.find_ctrl_focus", ID_Frame_FindCtrlFocus)
DEFINE_COMMAND("edit.find_in_files",   ID_Edit_FindInFiles)
DEFINE_COMMAND("edit.find_next",       ID_Edit_FindNext)
DEFINE_COMMAND("edit.find_prev",       ID_Edit_FindPrev)
DEFINE_COMMAND("edit.replace",         ID_Edit_Replace)
DEFINE_COMMAND("edit.goto",            ID_Edit_GoTo)
DEFINE_COMMAND("edit.last",            ID_Edit_Last)



DEFINE_COMMAND("file.first",            ID_File_First)
DEFINE_COMMAND("file.close",            ID_File_Close)
DEFINE_COMMAND("file.close_all",        ID_File_CloseAll)
DEFINE_COMMAND("file.save",             ID_File_Save)
DEFINE_COMMAND("file.save_as",          ID_File_SaveAs)
DEFINE_COMMAND("file.save_as_external", ID_File_SaveAsExternal)
DEFINE_COMMAND("file.bookmark",         ID_File_Bookmark)
DEFINE_COMMAND("file.share_view",       ID_File_ShareView)
DEFINE_COMMAND("file.page_setup",       ID_File_PageSetup)
DEFINE_COMMAND("file.print",            ID_File_Print)
DEFINE_COMMAND("file.back",             ID_File_Back)
DEFINE_COMMAND("file.forward",          ID_File_Forward)
DEFINE_COMMAND("file.reload",           ID_File_Reload)
DEFINE_COMMAND("file.stop",             ID_File_Stop)
DEFINE_COMMAND("file.run",              ID_File_Run)
DEFINE_COMMAND("file.last",             ID_File_Last)


DEFINE_COMMAND("frame.first",                    ID_Frame_First)
DEFINE_COMMAND("frame.url_ctrl",                 ID_Frame_UrlCtrl)
DEFINE_COMMAND("frame.find_ctrl",                ID_Frame_FindCtrl)
DEFINE_COMMAND("frame.toggle_full_screen",       ID_Frame_ToggleFullScreen)
DEFINE_COMMAND("frame.toggle_status_bar",        ID_Frame_ToggleStatusBar)
DEFINE_COMMAND("frame.toggle_standard_toolbar",  ID_Frame_ToggleStandardToolbar)
DEFINE_COMMAND("frame.toggle_link_toolbar",      ID_Frame_ToggleLinkToolbar)
DEFINE_COMMAND("frame.toggle_format_toolbar",    ID_Frame_ToggleFormatToolbar)
DEFINE_COMMAND("frame.toggle_project_panel",     ID_Frame_ToggleProjectPanel)    
DEFINE_COMMAND("frame.toggle_console_panel",     ID_Frame_ToggleConsolePanel)
DEFINE_COMMAND("frame.toggle_column_list_panel", ID_Frame_ToggleColumnListPanel)
DEFINE_COMMAND("frame.toggle_mark_manager",      ID_Frame_ToggleMarkManagerPanel)
DEFINE_COMMAND("frame.toggle_relationship_manager_panel", ID_Frame_ToggleRelationshipManagerPanel)
DEFINE_COMMAND("frame.show_column_list",         ID_Frame_ShowColumnList)
DEFINE_COMMAND("frame.show_project_panel",       ID_Frame_ShowProjectPanel)
DEFINE_COMMAND("frame.show_console_panel",       ID_Frame_ShowConsolePanel)
DEFINE_COMMAND("frame.last",                     ID_Frame_Last)



DEFINE_COMMAND("format.first",                    ID_Format_First)
DEFINE_COMMAND("format.settings",                 ID_Format_Settings)
DEFINE_COMMAND("format.rulers",                   ID_Format_Rulers)
DEFINE_COMMAND("format.font_face_combo",          ID_Format_FontFace_Combo)
DEFINE_COMMAND("format.font_size_combo",          ID_Format_FontSize_Combo)
DEFINE_COMMAND("format.toggle_wrap_text",         ID_Format_ToggleWrapText)
DEFINE_COMMAND("format.toggle_merge_cells",       ID_Format_ToggleMergeCells)
DEFINE_COMMAND("format.toggle_font_width",        ID_Format_ToggleFontWeight)
DEFINE_COMMAND("format.toggle_font_style",        ID_Format_ToggleFontStyle)
DEFINE_COMMAND("format.toggle_font_underline",    ID_Format_ToggleFontUnderline)
DEFINE_COMMAND("format.align_text_left",          ID_Format_AlignTextLeft)
DEFINE_COMMAND("format.align_text_center",        ID_Format_AlignTextCenter)
DEFINE_COMMAND("format.align_text_right",         ID_Format_AlignTextRight)
DEFINE_COMMAND("format.align_top",                ID_Format_AlignTop)
DEFINE_COMMAND("format.align_middle",             ID_Format_AlignMiddle)
DEFINE_COMMAND("format.align_bottom",             ID_Format_AlignBottom)
DEFINE_COMMAND("format.fill_color",               ID_Format_FillColor)
DEFINE_COMMAND("format.text_color",               ID_Format_TextColor)
DEFINE_COMMAND("format.line_color",               ID_Format_LineColor)
DEFINE_COMMAND("format.border",                   ID_Format_Border)
DEFINE_COMMAND("format.border_none",              ID_Format_Border_None)
DEFINE_COMMAND("format.border_left",              ID_Format_Border_Left)
DEFINE_COMMAND("format.border_right",             ID_Format_Border_Right)
DEFINE_COMMAND("format.border_top",               ID_Format_Border_Top)
DEFINE_COMMAND("format.border_bottom",            ID_Format_Border_Bottom)
DEFINE_COMMAND("format.border_bottom_thick",      ID_Format_Border_BottomThick)
DEFINE_COMMAND("format.border_bottom_double",     ID_Format_Border_BottomDouble)
DEFINE_COMMAND("format.border_top_bottom",        ID_Format_Border_TopBottom)
DEFINE_COMMAND("format.border_top_bottom_double", ID_Format_Border_TopBottomDouble)
DEFINE_COMMAND("format.border_top_bottom_thick",  ID_Format_Border_TopBottomThick)
DEFINE_COMMAND("format.border_outer",             ID_Format_Border_Outer)
DEFINE_COMMAND("format.border_outer_thick",       ID_Format_Border_OuterThick)
DEFINE_COMMAND("format.border_all",               ID_Format_Border_All)
DEFINE_COMMAND("format.last",                     ID_Format_Last)


DEFINE_COMMAND("project.first",                     ID_Project_First)
DEFINE_COMMAND("project.new",                       ID_Project_New)
DEFINE_COMMAND("project.new_tab",                   ID_Project_NewTab)
DEFINE_COMMAND("project.new_table",                 ID_Project_NewTable)
DEFINE_COMMAND("project.new_report",                ID_Project_NewReport)
DEFINE_COMMAND("project.new_query",                 ID_Project_NewQuery)
DEFINE_COMMAND("project.new_script",                ID_Project_NewScript)
DEFINE_COMMAND("project.open_file",                 ID_Project_OpenFile)
DEFINE_COMMAND("project.open_database",             ID_Project_OpenDatabase)
DEFINE_COMMAND("project.open_location",             ID_Project_OpenLocation)
DEFINE_COMMAND("project.open_location_complete",    ID_Project_OpenLocationComplete)
DEFINE_COMMAND("project.import",                    ID_Project_Import)
DEFINE_COMMAND("project.export",                    ID_Project_Export)
DEFINE_COMMAND("project.connect_external_database", ID_Project_ConnectExternalDatabase)
DEFINE_COMMAND("project.connect_external_tables",   ID_Project_ConnectExternalTables)
DEFINE_COMMAND("project.merge",                     ID_Project_Merge)
DEFINE_COMMAND("project.split",                     ID_Project_Split)
DEFINE_COMMAND("project.remove_dup_recs",           ID_Project_RemoveDupRecs)
DEFINE_COMMAND("project.relationship",              ID_Project_Relationship)
DEFINE_COMMAND("project.refresh_project",           ID_Project_RefreshProject)
DEFINE_COMMAND("project.project_properties",        ID_Project_ProjectProperties)
DEFINE_COMMAND("project.clean_project",             ID_Project_CleanProject)
DEFINE_COMMAND("project.close_project",             ID_Project_CloseProject)
DEFINE_COMMAND("project.help",                      ID_Project_Help)
DEFINE_COMMAND("project.home",                      ID_Project_Home)
DEFINE_COMMAND("project.reference",                 ID_Project_Reference)
DEFINE_COMMAND("project.resources",                 ID_Project_Resources)
DEFINE_COMMAND("project.support",                   ID_Project_Support)
DEFINE_COMMAND("project.contact_us",                ID_Project_ContactUs)
DEFINE_COMMAND("project.last",                      ID_Project_Last)

DEFINE_COMMAND("table.first",               ID_Table_First)
DEFINE_COMMAND("table.select_row",          ID_Table_SelectRow)
DEFINE_COMMAND("table.select_column",       ID_Table_SelectColumn)
DEFINE_COMMAND("table.insert_column_break", ID_Table_InsertColumnBreak)
DEFINE_COMMAND("table.remove_column_break", ID_Table_RemoveColumnBreak)
DEFINE_COMMAND("table.insert_group_break",  ID_Table_InsertGroupBreak)
DEFINE_COMMAND("table.remove_group_break",  ID_Table_RemoveGroupBreak)
DEFINE_COMMAND("table.edit_views",          ID_Table_EditViews)
DEFINE_COMMAND("table.hide_column",         ID_Table_HideColumn)
DEFINE_COMMAND("table.insert_columns",      ID_Table_InsertColumns)
DEFINE_COMMAND("table.delete_columns",      ID_Table_DeleteColumns)
DEFINE_COMMAND("table.insert_rows",         ID_Table_InsertRows)
DEFINE_COMMAND("table.delete_rows",         ID_Table_DeleteRows)
DEFINE_COMMAND("table.clear_cells",         ID_Table_ClearCells)
DEFINE_COMMAND("table.last",                ID_Table_Last)

// toolbar id's
DEFINE_COMMAND("toolbar.first",        ID_Toolbar_First)
DEFINE_COMMAND("toolbar.standard",     ID_Toolbar_Standard)
DEFINE_COMMAND("toolbar.format",       ID_Toolbar_Format)
DEFINE_COMMAND("toolbar.link",         ID_Toolbar_Link)
DEFINE_COMMAND("toolbar.last",         ID_Toolbar_Last)


DEFINE_COMMAND("view.first",                 ID_View_First)
DEFINE_COMMAND("view.view_switcher",         ID_View_ViewSwitcher)
DEFINE_COMMAND("view.switch_to_source_view", ID_View_SwitchToSourceView)
DEFINE_COMMAND("view.switch_to_design_view", ID_View_SwitchToDesignView)
DEFINE_COMMAND("view.switch_to_layout_view", ID_View_SwitchToLayoutView)
DEFINE_COMMAND("view.zoom_combo",            ID_View_ZoomCombo)
DEFINE_COMMAND("view.zoom_in",               ID_View_ZoomIn)
DEFINE_COMMAND("view.zoom_out",              ID_View_ZoomOut)
DEFINE_COMMAND("view.zoom_to_fit",           ID_View_ZoomToFit)
DEFINE_COMMAND("view.zoom_to_actual",        ID_View_ZoomToActual)
DEFINE_COMMAND("view.zoom_to_width",         ID_View_ZoomToWidth)
DEFINE_COMMAND("view.last",                  ID_View_Last)


DEFINE_COMMAND("window.first",            ID_Window_First)
DEFINE_COMMAND("window.cascade",          ID_Window_Cascade)
DEFINE_COMMAND("window.tile_vertical",    ID_Window_TileVertical)
DEFINE_COMMAND("window.tile_horizonatal", ID_Window_TileHorizontal)
DEFINE_COMMAND("window.next",             ID_Window_Next)
DEFINE_COMMAND("window.previous",         ID_Window_Previous)
DEFINE_COMMAND("window.current",          ID_Window_Current)
DEFINE_COMMAND("window.last",             ID_Window_Last)


END_COMMANDS()

